import { db } from './index.js';
import { boilerSpecifications } from './schema.js';

// Comprehensive boiler specifications database
// This includes popular models from major UK manufacturers

export const boilerData = [
  // Worcester Bosch Combi Boilers
  {
    manufacturer: 'Worcester Bosch',
    model: 'Greenstar 2000 25kW Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 25,
    flowRateLpm: 10.2,
    dimensions: { height: 720, width: 440, depth: 360 },
    weight: 42,
    efficiency: 94,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 10,
    isActive: true,
  },
  {
    manufacturer: 'Worcester Bosch',
    model: 'Greenstar 2000 30kW Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 30,
    flowRateLpm: 12.5,
    dimensions: { height: 720, width: 440, depth: 360 },
    weight: 43,
    efficiency: 94,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 10,
    isActive: true,
  },
  {
    manufacturer: 'Worcester Bosch',
    model: 'Greenstar 4000 25kW Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 25,
    flowRateLpm: 10.2,
    dimensions: { height: 720, width: 440, depth: 360 },
    weight: 44,
    efficiency: 94,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 12,
    isActive: true,
  },
  {
    manufacturer: 'Worcester Bosch',
    model: 'Greenstar 8000 Style 35kW Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 35,
    flowRateLpm: 14.3,
    dimensions: { height: 720, width: 440, depth: 360 },
    weight: 46,
    efficiency: 94,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 12,
    isActive: true,
  },

  // Worcester Bosch System Boilers
  {
    manufacturer: 'Worcester Bosch',
    model: 'Greenstar 2000 25kW System',
    fuelType: 'gas' as const,
    boilerType: 'system' as const,
    outputKw: 25,
    flowRateLpm: null,
    dimensions: { height: 720, width: 440, depth: 360 },
    weight: 40,
    efficiency: 94,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 10,
    isActive: true,
  },
  {
    manufacturer: 'Worcester Bosch',
    model: 'Greenstar 4000 30kW System',
    fuelType: 'gas' as const,
    boilerType: 'system' as const,
    outputKw: 30,
    flowRateLpm: null,
    dimensions: { height: 720, width: 440, depth: 360 },
    weight: 41,
    efficiency: 94,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 12,
    isActive: true,
  },

  // Vaillant Combi Boilers
  {
    manufacturer: 'Vaillant',
    model: 'ecoTEC Plus 825 25kW Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 25,
    flowRateLpm: 10.3,
    dimensions: { height: 720, width: 440, depth: 338 },
    weight: 42,
    efficiency: 94,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 10,
    isActive: true,
  },
  {
    manufacturer: 'Vaillant',
    model: 'ecoTEC Plus 832 32kW Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 32,
    flowRateLpm: 13.1,
    dimensions: { height: 720, width: 440, depth: 338 },
    weight: 43,
    efficiency: 94,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 10,
    isActive: true,
  },
  {
    manufacturer: 'Vaillant',
    model: 'ecoTEC Plus 835 35kW Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 35,
    flowRateLpm: 14.3,
    dimensions: { height: 720, width: 440, depth: 338 },
    weight: 44,
    efficiency: 94,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 10,
    isActive: true,
  },

  // Vaillant System Boilers
  {
    manufacturer: 'Vaillant',
    model: 'ecoTEC Plus 612 System 12kW',
    fuelType: 'gas' as const,
    boilerType: 'system' as const,
    outputKw: 12,
    flowRateLpm: null,
    dimensions: { height: 720, width: 440, depth: 338 },
    weight: 38,
    efficiency: 94,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 10,
    isActive: true,
  },
  {
    manufacturer: 'Vaillant',
    model: 'ecoTEC Plus 618 System 18kW',
    fuelType: 'gas' as const,
    boilerType: 'system' as const,
    outputKw: 18,
    flowRateLpm: null,
    dimensions: { height: 720, width: 440, depth: 338 },
    weight: 39,
    efficiency: 94,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 10,
    isActive: true,
  },

  // Ideal Combi Boilers
  {
    manufacturer: 'Ideal',
    model: 'Logic Max 24kW Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 24,
    flowRateLpm: 9.8,
    dimensions: { height: 700, width: 395, depth: 290 },
    weight: 39,
    efficiency: 93,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 10,
    isActive: true,
  },
  {
    manufacturer: 'Ideal',
    model: 'Logic Max 30kW Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 30,
    flowRateLpm: 12.2,
    dimensions: { height: 700, width: 395, depth: 290 },
    weight: 40,
    efficiency: 93,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 10,
    isActive: true,
  },
  {
    manufacturer: 'Ideal',
    model: 'Vogue Max 26kW Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 26,
    flowRateLpm: 10.6,
    dimensions: { height: 700, width: 395, depth: 290 },
    weight: 40,
    efficiency: 93.2,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 12,
    isActive: true,
  },

  // Baxi Combi Boilers
  {
    manufacturer: 'Baxi',
    model: 'EcoBlue Advance 24kW Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 24,
    flowRateLpm: 9.8,
    dimensions: { height: 700, width: 400, depth: 290 },
    weight: 38,
    efficiency: 93,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 7,
    isActive: true,
  },
  {
    manufacturer: 'Baxi',
    model: 'EcoBlue Advance 30kW Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 30,
    flowRateLpm: 12.2,
    dimensions: { height: 700, width: 400, depth: 290 },
    weight: 39,
    efficiency: 93,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 7,
    isActive: true,
  },
  {
    manufacturer: 'Baxi',
    model: 'Duo-tec 28kW Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 28,
    flowRateLpm: 11.4,
    dimensions: { height: 700, width: 400, depth: 290 },
    weight: 40,
    efficiency: 94,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 10,
    isActive: true,
  },

  // Viessmann Combi Boilers
  {
    manufacturer: 'Viessmann',
    model: 'Vitodens 050-W 29kW Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 29,
    flowRateLpm: 11.8,
    dimensions: { height: 720, width: 450, depth: 360 },
    weight: 41,
    efficiency: 94,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 10,
    isActive: true,
  },
  {
    manufacturer: 'Viessmann',
    model: 'Vitodens 100-W 35kW Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 35,
    flowRateLpm: 14.3,
    dimensions: { height: 720, width: 450, depth: 360 },
    weight: 43,
    efficiency: 94,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 12,
    isActive: true,
  },

  // Alpha Combi Boilers
  {
    manufacturer: 'Alpha',
    model: 'E-Tec Plus 25kW Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 25,
    flowRateLpm: 10.2,
    dimensions: { height: 700, width: 400, depth: 295 },
    weight: 38,
    efficiency: 93,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 10,
    isActive: true,
  },
  {
    manufacturer: 'Alpha',
    model: 'E-Tec Plus 33kW Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 33,
    flowRateLpm: 13.5,
    dimensions: { height: 700, width: 400, depth: 295 },
    weight: 39,
    efficiency: 93,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 10,
    isActive: true,
  },

  // Potterton Combi Boilers
  {
    manufacturer: 'Potterton',
    model: 'Gold 24 HE Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 24,
    flowRateLpm: 9.8,
    dimensions: { height: 700, width: 400, depth: 300 },
    weight: 37,
    efficiency: 92.5,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 7,
    isActive: true,
  },
  {
    manufacturer: 'Potterton',
    model: 'Gold 28 HE Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 28,
    flowRateLpm: 11.4,
    dimensions: { height: 700, width: 400, depth: 300 },
    weight: 38,
    efficiency: 92.5,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 7,
    isActive: true,
  },

  // Glow-worm Combi Boilers
  {
    manufacturer: 'Glow-worm',
    model: 'Energy 25S Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 25,
    flowRateLpm: 10.2,
    dimensions: { height: 700, width: 400, depth: 305 },
    weight: 39,
    efficiency: 93,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 8,
    isActive: true,
  },
  {
    manufacturer: 'Glow-worm',
    model: 'Energy 30S Combi',
    fuelType: 'gas' as const,
    boilerType: 'combi' as const,
    outputKw: 30,
    flowRateLpm: 12.2,
    dimensions: { height: 700, width: 400, depth: 305 },
    weight: 40,
    efficiency: 93,
    erpRating: 'A',
    flueType: 'horizontal',
    minGasPressure: 17,
    maxGasPressure: 25,
    warranty: 8,
    isActive: true,
  },
];

export async function seedBoilers() {
  console.log('Seeding boiler specifications...');

  try {
    // Delete existing boilers
    await db.delete(boilerSpecifications);

    // Insert new boilers
    await db.insert(boilerSpecifications).values(boilerData);

    console.log(`✅ Successfully seeded ${boilerData.length} boiler specifications`);
  } catch (error) {
    console.error('❌ Error seeding boilers:', error);
    throw error;
  }
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedBoilers()
    .then(() => process.exit(0))
    .catch(() => process.exit(1));
}
