#!/bin/bash

# PHM Unraid Setup Script
# One-command installation for Unraid NAS
# Usage: bash scripts/setup-unraid.sh

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
APPDATA_PATH="${APPDATA_PATH:-/mnt/user/appdata/phm}"
WEB_PORT="${WEB_PORT:-3000}"
API_PORT="${API_PORT:-3001}"
DB_PORT="${DB_PORT:-5432}"

echo ""
echo -e "${BLUE}╔════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║                                                    ║${NC}"
echo -e "${BLUE}║        PHM - Heating Industry CRM Platform         ║${NC}"
echo -e "${BLUE}║             Unraid Setup Script                    ║${NC}"
echo -e "${BLUE}║                                                    ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════╝${NC}"
echo ""

# Function to generate secure random password
generate_password() {
    openssl rand -base64 32 | tr -d "=+/" | cut -c1-32
}

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Validate prerequisites
echo -e "${BLUE}📋 Checking prerequisites...${NC}"

if ! command_exists docker; then
    echo -e "${RED}❌ Docker is not installed. Please install Docker first.${NC}"
    exit 1
fi

if ! command_exists docker-compose && ! docker compose version >/dev/null 2>&1; then
    echo -e "${RED}❌ Docker Compose is not installed. Please install Docker Compose first.${NC}"
    exit 1
fi

if ! command_exists openssl; then
    echo -e "${RED}❌ OpenSSL is not installed. Please install OpenSSL first.${NC}"
    exit 1
fi

echo -e "${GREEN}✅ All prerequisites met${NC}"
echo ""

# Create appdata directories
echo -e "${BLUE}📁 Creating data directories...${NC}"
mkdir -p "$APPDATA_PATH/postgres"
mkdir -p "$APPDATA_PATH/uploads"
mkdir -p "$APPDATA_PATH/init-flag"
echo -e "${GREEN}✅ Directories created at $APPDATA_PATH${NC}"
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo -e "${YELLOW}⚠️  .env file already exists${NC}"
    read -p "Do you want to regenerate it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${BLUE}ℹ️  Using existing .env file${NC}"
        SKIP_ENV=true
    fi
fi

# Generate .env file
if [ "$SKIP_ENV" != true ]; then
    echo -e "${BLUE}🔐 Generating secure credentials...${NC}"

    # Generate passwords
    DB_PASSWORD=$(generate_password)
    JWT_SECRET=$(generate_password)$(generate_password)  # 64 chars for extra security
    JWT_REFRESH_SECRET=$(generate_password)$(generate_password)
    ADMIN_PASSWORD=$(generate_password | cut -c1-16)  # Shorter for manual entry

    # Get server IP (try to auto-detect)
    SERVER_IP=$(ip route get 1 | sed -n 's/^.*src \([0-9.]*\) .*$/\1/p')
    if [ -z "$SERVER_IP" ]; then
        SERVER_IP="localhost"
    fi

    # Create .env file
    cat > .env << EOF
# PHM Environment Configuration (Generated by setup-unraid.sh)
# Generated: $(date)

# ========================================
# Database Configuration
# ========================================
DB_PASSWORD=$DB_PASSWORD

# ========================================
# JWT Secrets (Auto-generated)
# ========================================
JWT_SECRET=$JWT_SECRET
JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET

# JWT Expiration
JWT_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

# ========================================
# API Configuration
# ========================================
PORT=$API_PORT
NODE_ENV=production
BASE_URL=http://$SERVER_IP:$WEB_PORT

# ========================================
# CORS Configuration
# ========================================
# Allow all origins (adjust for production security)
CORS_ORIGIN=*

# ========================================
# Frontend Configuration
# ========================================
VITE_API_URL=http://$SERVER_IP:$API_PORT
WEB_PORT=$WEB_PORT

# ========================================
# Initial Admin User
# ========================================
INITIAL_ADMIN_EMAIL=admin@phm.local
INITIAL_ADMIN_PASSWORD=$ADMIN_PASSWORD

# ========================================
# Unraid Specific
# ========================================
APPDATA_PATH=$APPDATA_PATH

# ========================================
# Optional: AI Features (for Phase 2)
# ========================================
# GEMINI_API_KEY=your-gemini-api-key-here
# DEEPGRAM_API_KEY=your-deepgram-api-key-here

# ========================================
# Optional: Email Configuration (for Phase 3)
# ========================================
# SMTP_HOST=smtp.example.com
# SMTP_PORT=587
# SMTP_USER=your-email@example.com
# SMTP_PASSWORD=your-smtp-password
# SMTP_FROM=noreply@phm.local
EOF

    echo -e "${GREEN}✅ Secure credentials generated and saved to .env${NC}"
    echo ""
fi

# Display configuration
echo -e "${BLUE}📝 Configuration Summary:${NC}"
echo -e "   ${YELLOW}Appdata Path:${NC} $APPDATA_PATH"
echo -e "   ${YELLOW}Web Port:${NC} $WEB_PORT"
echo -e "   ${YELLOW}API Port:${NC} $API_PORT"
echo -e "   ${YELLOW}Database Port:${NC} $DB_PORT"
echo ""

# Ask for confirmation
read -p "Continue with installation? (Y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Nn]$ ]]; then
    echo -e "${RED}Installation cancelled${NC}"
    exit 0
fi

# Stop existing containers if running
echo -e "${BLUE}🛑 Stopping any existing PHM containers...${NC}"
docker-compose -f docker-compose.unraid.yml down 2>/dev/null || true
echo ""

# Build and start services
echo -e "${BLUE}🏗️  Building and starting services...${NC}"
echo -e "${YELLOW}This may take a few minutes on first run...${NC}"
echo ""

if docker compose version >/dev/null 2>&1; then
    docker compose -f docker-compose.unraid.yml up -d --build
else
    docker-compose -f docker-compose.unraid.yml up -d --build
fi

echo ""
echo -e "${GREEN}✅ Services started successfully!${NC}"
echo ""

# Wait for services to be healthy
echo -e "${BLUE}⏳ Waiting for services to be healthy...${NC}"
sleep 5

# Check service status
echo ""
echo -e "${BLUE}📊 Service Status:${NC}"
if docker compose version >/dev/null 2>&1; then
    docker compose -f docker-compose.unraid.yml ps
else
    docker-compose -f docker-compose.unraid.yml ps
fi

# Display success message and credentials
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                                                    ║${NC}"
echo -e "${GREEN}║           ✅ Installation Complete! ✅              ║${NC}"
echo -e "${GREEN}║                                                    ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BLUE}🌐 Access your PHM platform:${NC}"
echo -e "   ${YELLOW}Web Interface:${NC} http://$SERVER_IP:$WEB_PORT"
echo -e "   ${YELLOW}API Endpoint:${NC}  http://$SERVER_IP:$API_PORT"
echo ""
echo -e "${BLUE}🔑 Login Credentials:${NC}"

# Extract credentials from .env
ADMIN_EMAIL=$(grep INITIAL_ADMIN_EMAIL .env | cut -d '=' -f2)
ADMIN_PASS=$(grep INITIAL_ADMIN_PASSWORD .env | cut -d '=' -f2)

echo -e "   ${YELLOW}Email:${NC}    $ADMIN_EMAIL"
echo -e "   ${YELLOW}Password:${NC} $ADMIN_PASS"
echo ""
echo -e "${RED}⚠️  IMPORTANT: Change the admin password immediately after first login!${NC}"
echo ""
echo -e "${BLUE}📚 Useful Commands:${NC}"
echo -e "   ${YELLOW}View logs:${NC}        docker-compose -f docker-compose.unraid.yml logs -f"
echo -e "   ${YELLOW}Stop services:${NC}    docker-compose -f docker-compose.unraid.yml down"
echo -e "   ${YELLOW}Restart services:${NC} docker-compose -f docker-compose.unraid.yml restart"
echo -e "   ${YELLOW}Update:${NC}           git pull && bash scripts/setup-unraid.sh"
echo ""
echo -e "${BLUE}💾 Data Location:${NC}"
echo -e "   ${YELLOW}Database:${NC}  $APPDATA_PATH/postgres"
echo -e "   ${YELLOW}Uploads:${NC}   $APPDATA_PATH/uploads"
echo ""
echo -e "${GREEN}Happy surveying! 🎉${NC}"
echo ""
